[package]

name = "event"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[lib]

name = "event"
path = "src/lib.rs"

[dependencies.typemap]

git = "https://github.com/reem/rust-typemap.git"

[dependencies.unsafe-any]

git = "https://github.com/reem/rust-unsafe-any.git"

